server=/turktelekom.com.tr/#
server=/ttmobil.com.tr/#
server=/netmera.com/#
server=/ttnet.com.tr/#
server=/tivibu.com.tr/#
rebind-domain-ok=/turktelekom.com.tr/
rebind-domain-ok=/ttmobil.com.tr/
rebind-domain-ok=/netmera.com/
rebind-domain-ok=/ttnet.com.tr/
server=/avea.com.tr/#
server=/clevertap-prod.com/#
rebind-domain-ok=/avea.com.tr/
