#!/bin/sh /etc/rc.common
START=5
STOP=10

start() {
    # Boş dosya oluştur (dnsmasq bad symlink hatası vermesin)
    touch /tmp/hagezi_multi.conf
    
    # Symlink kur
    mkdir -p /etc/dnsmasq.d
    ln -sf /tmp/hagezi_multi.conf /etc/dnsmasq.d/hagezi_multi.conf
}