# Archer C50 v6 Gaming Optimizasyonu
net.ipv4.tcp_congestion_control=cubic
net.core.netdev_max_backlog=1024
net.core.rmem_max=262144
net.core.wmem_max=262144
net.core.rmem_default=163840
net.core.wmem_default=163840
net.ipv4.tcp_fin_timeout=15
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_ecn=0
net.netfilter.nf_conntrack_max=2048
net.ipv4.tcp_slow_start_after_idle=0

