echo "==> Kernel config optimizations"

grep -q "^CONFIG_KERNEL_SWAP=y$" .config || cat >> .config << 'EOF'

# ZRAM için SWAP desteği (ZORUNLU)
CONFIG_KERNEL_SWAP=y

# Debug/Profil çıkar
CONFIG_KERNEL_DEBUG_INFO=n
CONFIG_KERNEL_DEBUG_KERNEL=n
CONFIG_KERNEL_KALLSYMS=n
CONFIG_KERNEL_CRASHLOG=n
CONFIG_KERNEL_ELF_CORE=n
CONFIG_KERNEL_PROVE_LOCKING=n
CONFIG_KERNEL_SECCOMP=n
CONFIG_KERNEL_NAMESPACES=n
CONFIG_KERNEL_CGROUPS=n

# Sıkıştırma optimizasyonu
CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=512
CONFIG_USE_MKLIBS=y
CONFIG_STRIP_KERNEL_EXPORTS=y

# ZRAM için
CONFIG_ZSMALLOC=y
CONFIG_ZRAM=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
EOF

fi