name: Build OpenWrt 25.12.5

on:
  workflow_dispatch:

env:
  OPENWRT_VERSION: v25.12.5

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex g++ gawk gcc-multilib gettext \
            git libncurses-dev libssl-dev python3-setuptools rsync \
            swig unzip zlib1g-dev file wget curl

      - name: Clone OpenWrt
        run: |
          git clone --depth=1 --branch ${OPENWRT_VERSION} https://github.com/openwrt/openwrt.git

      - name: Update feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare build
        working-directory: openwrt
        run: |
          chmod +x ../scripts/*.sh
          ../scripts/prepare.sh

      - name: Copy custom files
        run: |
          mkdir -p openwrt/files
          cp -a files/. openwrt/files/

      - name: Optimize build
        working-directory: openwrt
        run: |
          ../scripts/optimize.sh

      - name: Show target
        working-directory: openwrt
        run: |
          grep '^CONFIG_TARGET' .config

      - name: Download sources
        working-directory: openwrt
        run: |
          make download -j"$(nproc)"

      - name: Build firmware
        working-directory: openwrt
        run: |
          make -j"$(nproc)" V=s

      - name: Generate checksums
        working-directory: openwrt/bin/targets
        run: |
          find . -type f ! -name sha256sums.txt -exec sha256sum {} \; | sort > sha256sums.txt

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-c50v6-${{ github.run_number }}
          compression-level: 0
          if-no-files-found: error
          path: |
            openwrt/bin/targets/**